NAME = BraiiiiiiinnnzzzZ

SRC =	main.cpp\
		Zombie.cpp\
		newZombie.cpp\
		randomChump.cpp\

CC = c++

FLAGS = -Wall -Wextra -Werror -std=c++98
all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(FLAGS) $(SRC) -o $(NAME)

clean:
	rm -f $(NAME)

re: clean all
